name: Review and deploy Development environment 🚀

on:
  workflow_dispatch:
    inputs:
      aws-region:
        description: "AWS Region to deploy into"
        required: true
        default: "us-east-1"
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Terraform to Dev
    runs-on: ubuntu-latest

    env:
      TF_LOG: INFO
      AWS_REGION: ${{ github.event.inputs.aws-region }}
      TF_WORKING_DIR: ./terraform/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws-region }}

      - name: Initialize Terraform
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Validate Terraform
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      - name: Plan Terraform
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=tfplan -input=false

      - name: Apply Terraform (Auto-approve)
        if: github.ref == 'refs/heads/dev' || github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan

